version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  go-bourbaki:
    ports:
     - "2000:2000"
    image: go-bourbaki 
    environment:
      - VIRTUAL_HOST=bourbaki.doelia.fr
      - VIRTUAL_PORT=2000

  realtimeboard:
    image: realtimeboard 
    environment:
      - VIRTUAL_HOST=whiteboard.doelia.fr
      - VIRTUAL_PORT=8080

  minelia:
    image: minelia
    environment:
      - VIRTUAL_HOST=minelia.doelia.fr

  dominion:
    build: ./dominion-proxy
    environment:
      - VIRTUAL_HOST=dominion.doelia.fr
  dominion-server:
    image: dominion-server 
  dominion-client:
    image: dominion-client

